version: '3.1'

services:
  rasa:
    build: .
    volumes:
      - .:/app
    ports:
      - 5005:5005
    networks:
      - new_netw

  telgram:
    build: ./telegram
    volumes:
      - ./telegram:/app1
    ports:
      - 5002:5002 
    networks:
      - new_netw

networks:
  new_netw:
    driver: bridge
